### PR TITLE
[ENH, MRG] Match ECoG data with sEEG

### PR DESCRIPTION
**Pull request by alexrockhill**
I think since the ECoG tutorial pulls directly from OpenNeuro, we could remove the data in here.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@larsoner merge if happy

**Comment by larsoner** [comment]
Looks like this will break `examples/visualization/3d_to_2d.py`:
```
$ git grep sample_ecog
doc/overview/datasets_index.rst::func:`mne.datasets.misc.data_path`. Data exists at ``/ecog/sample_ecog.mat``.
examples/visualization/3d_to_2d.py:path_data = mne.datasets.misc.data_path() + '/ecog/sample_ecog.mat'
```

**Comment by alexrockhill** [comment]
Whew, okay good call @larsoner. I was going to refactor into one `fif` file with channel locations as that is hopefully the ideal MNE workflow using the GUI but then I saw it wasn't used anymore in the ECoG tutorial. I'll go ahead and do that and write a PR for `3d_to_2d`.

**Comment by alexrockhill** [comment]
Hey @libertyh, I used the data you posted for the frontiers paper for this, is that okay? Also do you have even a short ephys recording for the test subject? I think that would be really great for the examples.

**Comment by alexrockhill** [comment]
```
import numpy as np
import os.path as op
import mne
from mne.io import concatenate_raws, read_raw_edf
from mne.datasets import eegbci
from mne.datasets import fetch_fsaverage
from scipy.io import loadmat
from mne.minimum_norm import make_inverse_operator, apply_inverse
from scipy.spatial import distance_matrix

# load EEG BCI motor execution runs
raw_fnames = eegbci.load_data(1, [3, 7, 11])
raws = [read_raw_edf(f, preload=True) for f in raw_fnames]
raw = concatenate_raws(raws)

# estimate stc on fsaverage
fs_dir = fetch_fsaverage(verbose=True)
subjects_dir = op.dirname(fs_dir)
subject = 'fsaverage'
trans = 'fsaverage'  # MNE has a built-in fsaverage transformation
src = op.join(fs_dir, 'bem', 'fsaverage-ico-5-src.fif')
bem = op.join(fs_dir, 'bem', 'fsaverage-5120-5120-5120-bem-sol.fif')

new_names = dict(
    (ch_name,
     ch_name.rstrip('.').upper().replace('Z', 'z').replace('FP', 'Fp'))
    for ch_name in raw.ch_names)
raw.rename_channels(new_names)

montage = mne.channels.make_standard_montage('standard_1005')
raw.set_montage(montage)
raw.set_eeg_reference(projection=True)  # needed for inverse modeling

events, event_id = mne.events_from_annotations(raw)
epochs = mne.Epochs(raw, events, event_id=1)

noise_cov = mne.compute_covariance(epochs)

fwd = mne.make_forward_solution(raw.info, trans=trans, src=src,
                                bem=bem, eeg=True, mindist=5.0, n_jobs=1)
inv = make_inverse_operator(raw.info, fwd, noise_cov)

evoked = epochs.average()
stc = apply_inverse(evoked, inv)

# use channel positions that Liberty made available
chs = loadmat('~/Downloads/test_subj/elecs/TDT_elecs_all.mat')

# fix grid positions
for i, name in enumerate(ch_names):
    if 'G' in name:
        chs['elecmatrix'][i] += np.array([-1.5, -1.5, -3])
    if 'OMFG' in name:
        chs['elecmatrix'][i] += np.array([0.39, 0.68, 3.87])

ch_names = [ch[0][0] for ch in chs['eleclabels']]
info = mne.create_info(ch_names, stc.sfreq, ['ecog' if 'G' in name else 'seeg' for name in ch_names])
montage = mne.channels.make_dig_montage(dict(zip(ch_names, chs['elecmatrix'] / 1000)), coord_frame='mri')
montage.add_estimated_fiducials('sample_ecog', './ecog')

# transform montage to fsaverage
mri_mni_t = mne.read_talxfm('sample_ecog', './ecog')
montage.apply_trans(mri_mni_t)

ch_pos = montage.get_positions()['ch_pos']
verts = np.concatenate([inv['src'][0]['rr'][stc.lh_vertno], inv['src'][1]['rr'][stc.rh_vertno]])
dists = distance_matrix(np.array(list(ch_pos.values())), verts)
info.set_montage(montage)

# assign data by nearest stc vert
data = np.zeros((len(info.ch_names), evoked.times.size))
for i, pos in enumerate(ch_pos.values()):
    data[i] = stc.data[np.argmin(dists[i])]

# center and scale
data -= data.mean(axis=0)
data *= 5e-5

# use MRI coord montage, make raw
montage = mne.channels.make_dig_montage(dict(zip(ch_names, chs['elecmatrix'] / 1000)), coord_frame='mri')
montage.add_estimated_fiducials('sample_ecog', './ecog')
info.set_montage(montage)
raw = mne.io.RawArray(data, info)
raw.save('./ecog/sample_ecog_ieeg.fif', overwrite=True)

# plot to confirm
trans = mne.channels.compute_native_head_t(montage)
brain = mne.viz.Brain('sample_ecog', subjects_dir='./ecog/', alpha=0.25)
brain.add_sensors(raw.info, trans)
```

**Comment by alexrockhill** [comment]
Screen Shot 2021-09-16 at 3 16 24 PM
Screen Shot 2021-09-16 at 3 16 58 PM

Ok, I just used the EEG BCI data to make a source estimate and assign the nearest source vertex to that sensor. I think this works until we ever get the data for this dataset.

This would be really nice to have formatted for ECoG use with the GUI and examples/tutorials.

**Comment by alexrockhill** [comment]
```
import os.path as op
import mne
import nibabel as nib

CT_aligned = nib.load('/Users/alexrockhill/education/UO/SwannLab/test_subj/CT/rCT.nii')

misc_path = '.'
subj_trans = mne.coreg.estimate_head_mri_t(
    'sample_ecog', op.join(misc_path, 'ecog'))
raw = mne.io.read_raw(op.join(misc_path, 'ecog', 'sample_ecog_ieeg.fif'))

gui = mne.gui.locate_ieeg(raw.info, subj_trans, CT_aligned,
                          subject='sample_ecog',
                          subjects_dir=op.join(misc_path, 'ecog'))

```

Huh the grids are off but the SEEG looks spot on

Screen Shot 2021-09-16 at 4 07 10 PM
Screen Shot 2021-09-16 at 4 08 12 PM

I'll fix that really quick

**Comment by alexrockhill** [comment]
The `reg_affine` is 

```
import os.path as op
import numpy as np
import nibabel as nib

CT_aligned = nib.load('/Users/alexrockhill/education/UO/SwannLab/test_subj/CT/rCT.nii')
CT_orig = nib.load('/Users/alexrockhill/education/UO/SwannLab/test_subj/CT/CT.nii')

reg_affine = np.linalg.solve(CT_orig.affine, CT_aligned.affine)

```

```
array([[  2.03589662,   0.19925852,  -0.09863109, -26.74088954],
       [  0.11797162,  -0.19806079,   2.03498453,  12.04124976],
       [  0.07361463,  -0.7924367 ,  -0.08139376, 172.05299634],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
```

**Comment by alexrockhill** [comment]
Man that took a lot longer than I thought to click through the two grids by hand, can't wait for the automated version. This is ready to merge though if it's okay with everyone

**Comment by agramfort** [comment]
@larsoner merge if happy. LGTM

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-misc-data/releases/tag/0.22

**Pull request merged**
