### PR TITLE
[WIP] Adding real ecog/seeg data in EDF format

### LINKED ISSUE #2: Adding EDF version of the ECoG data
@larsoner is it possible to add an EDF version using the gist here: https://gist.github.com/skjerns/bc660ef59dca0dbd53f00ed38c42f6be

This would just create a fake EEG data with the corresponding electrodes in sample_ecog.mat.

**Reason:**
The reason is that inside mne-bids, right now the package needs an EEG file to be in an accepted "rawfile" format when performing writing. For EEG/MEG, these are readily available, but for iEEG this is only in the form of EDF and BV. This isn't an issue when using the existing EDF/BV datasets in mne, but none have electrode coordinates (i.e. a montage). The sample_ecog.mat  here has a montage, but no corresponding iEEG  data.

To make a good iEEG example in mne-bids, it would be helpful instead to just get a fake EDF file that has the same data as in sample_ecog.mat, and then sample_ecog.mat has the fake electrode coordinates.

**Reference issues:** 
- https://github.com/mne-tools/mne-bids/issues/404
- https://github.com/mne-tools/mne-bids/pull/390

### PR DESCRIPTION
**Pull request by adam2392**
Closes: #2 

The datasets are severely trimmed and downsampled, but the channels and the "nature" of the data is still intact (e.g. channel metadata, some test annotations, etc.).

All were de-anonymized and essentially trimmed down to approximately 10-30 seconds of data. For the  ECoG, i used the same electrode coordinates as in `sample_ecog.mat`, and just renamed the channels. 

I added some additional files, required by BIDS.

### CODE REVIEW

**Comment by agramfort** [comment]
the files pass the bids validator?

**Comment by larsoner** [comment]
Please do not merge until we follow the process outlined in https://github.com/mne-tools/mne-misc-data/issues/2#issuecomment-624754128 or otherwise modify the process there

**Comment by adam2392** [comment]
> the files pass the bids validator?

No, since its not in the BIDS file tree, but it will once it's written using mne-bids. If this isn't desirable, then I can just change the names so ppl don't think its fully bids-compatible.

**Comment by agramfort** [comment]
I think it's misleading to use bids naming outside of a proper bids dataset

>

**Pull request merged**
