### PR TITLE
[ENH] Added Imaging data for seeg subject

### PR DESCRIPTION
**Pull request by alexrockhill**
This adds a CT and MRI (defaced) for a stereoEEG subject. The data file had to change as well to match the subject. The task is a forced two-choice button task that has a nice evoked response for the examples as well. This way the tutorial can extend earlier to finding electrode contact locations and not just assume that the user already has them.

### CODE REVIEW

**Comment by larsoner** [comment]
Need to update version.txt, too

**Comment by alexrockhill** [comment]
This will break the seeg example in mne-python by the way which I am working on fixing.

**Comment by larsoner** [comment]
It won't break it on `main` / until you update this:

https://github.com/mne-tools/mne-python/blob/main/mne/datasets/utils.py#L257

Which you should do in your PR that uses the new data

**Comment by larsoner** [comment]
0.10 released with locally computed hash 3e80520df1af48dfbc55ef195574e1d2

**Pull request merged**
