### PR TITLE
[ENH, MRG] Change sEEG raw coordinate frame

### PR DESCRIPTION
**Pull request by alexrockhill**
So I ended up just confusing myself a lot trying to finagle the coordinate frames for sEEG when the simplest option I think is best which is to just equate the head and mri coordinate frames for sEEG. I was trying to use the `get_mni_fiducials` which Eric recommended. This takes the fiducials that someone did on fsaverage at some point and transforms them using Talairach to the subject's mri. In `plot_alignment` this is used when `trans='estimate'`, which tipped me off that maybe this was just a bit too confusing. What this actually does is define the "head" coordinate frame to be an estimate of "mri"/surface RAS. However, even if fiducials are not provided, `info.set_montage(montage)` where `montage` is "head" coordinates will leave the coordinates without transforming them. The only disadvantage to this approach is that there are no fiducials but they could be picked manually or estimated separately using `mne.coreg.get_mni_fiducials`, the main thing is that relying on these estimated fiducials to define a coordinate frame for sEEG is confusing because it is very unclear what the "head" coordinate frame even is in that case. Therefore, I think it's simplest and best to just define the "head" coordinate frame as identical to "mri" and leave it at that. This PR just gets rid of the round trip transformation to estimated "head" coordinates and has the `raw` object have coordinates in "mri" space. 

Whew, hopefully the end of coordinate frame wrangling and moving on to other aspects.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
-1 on this, we have had many discussions of this head vs unknown vs MRi and why it matters in the past. I don't have time to look now, but if nobody else can find them I can look next week.

> The only disadvantage to this approach is that there are no fiducials

The big disadvantage to equating them is that it is incorrect. The head coordinate frame is well defined by LPA/Nasion/RPA, and it's (effectively) never the same as surface RAS. So by saying that they are the same, you are doing something wrong. This makes things like topomaps (or anything in head coordinates) silently no longer mean the same thing across datasets.

I'd prefer to give people an easy way to get from MRI to head with as little work as possible. After that I'd rather make it easier to keep everything in native MRI coordinates and never worry about head (until something needs it). I'd rather not ever (incorrectly) equate the two coordinate frames.

**Comment by alexrockhill** [comment]
> The big disadvantage to equating them is that it is incorrect. The head coordinate frame is well defined by LPA/Nasion/RPA, and it's (effectively) never the same as surface RAS. So by saying that they are the same, you are doing something wrong. This makes things like topomaps (or anything in head coordinates) silently no longer mean the same thing across datasets.

But there is no digitization coordinate frame, the only LPA/Nasion/RPA are in the Freesurfer T1/brain images. Thus, I think it makes sense and actually is correct to say that this is the head coordinate frame; for SEEG it's as your Polemus pen/other digitization system is your Freesurfer MRI (really it's the CT but it is coregistered). I think that's where all my confusion has come from, I was trying to wrap my head around what the "head" coordinate frame for SEEG is and I think how we were defining it was just an estimate of surface RAS when we could just equate them and it would be identically aligned as described in the last post.

> I'd prefer to give people an easy way to get from MRI to head with as little work as possible. After that I'd rather make it easier to keep everything in native MRI coordinates and never worry about head (until something needs it). I'd rather not ever (incorrectly) equate the two coordinate frames.

What is the correct "head" coordinate frame? Where are the fiducials that define it coming from? This doesn't make sense to me.

**Comment by alexrockhill** [comment]
See https://github.com/mne-tools/mne-python/pull/9585 in `plot_alignment` as well where the default `trans=None` assumes the identity transformation matrix. I assume based on this that it is a common or at least not unheard of use case to have "head" be the same as "mri". In the PR, I added a warning since I think this should not be done silently.

**Comment by larsoner** [comment]
> What is the correct "head" coordinate frame?

I think this is where you are getting stuck. Each person has a unique head coordinate frame defined by the intersection between a line from LPA to RPA (defining +X) and one orthogonal to it through their nasion (defining +Y), plus an axis orthogonal to it in a right-handed coordinate system (defining +Z).  This is the correct / canonical coordinate frame for that individual. Thus, no matter what coordinate frame you have your LPA/Nasion/RPA in -- be it unknown digitizer coordinates, or MRI coordinates -- you can easily, directly, uniquely construct the transformation from those three points to the individual's head coordinate frame.

I'll respond to the other points, but hopefully you can see a consistent view / response already based on this definition...

> But there is no digitization coordinate frame...

Agreed, for sEEG there is no digitizer / unknown coordinate frame -- just MRI surface RAS.

> the only LPA/Nasion/RPA are in the Freesurfer T1/brain images

Agreed. However, given LPA/Nasion/RPA in MRI surface RAS coordinates, you can uniquely define the MRI<->head transformation, and it will never (in practice) be identity.

> Thus, I think it makes sense and actually is correct to say that this is the head coordinate frame; for SEEG it's as your Polemus pen/other digitization system is your Freesurfer MRI (really it's the CT but it is coregistered). 

For Polhemus, points you get natively from the system are actually typically in some coordinate frame that is native to the device (these come in as "unknown", not "head"). If you have LPA/Nasion/RPA, you can get from unknown<->head -- and we do this automatically in `set_montage`.

For MRI, if you can get LPA/Nasion/RPA in MRI surface RAS coordinates (e.g., by actually picking points with a mouse as in `mne coreg` or by estimating them in a "good enough" way with get_mni_fiducials), you can not only put these points in the head coordinate frame, but you also get the mri<->head transformation from it.

> plot_alignment as well where the default trans=None assumes the identity transformation matrix.

I'd be +1 for deprecating this actually. I think it does more harm than good in these situations, and it's mostly IIRC a remnant of years ago when we had the Montage class and *did not* transform to the head coordinate frame automatically!

**Comment by alexrockhill** [comment]
> Agreed. However, given LPA/Nasion/RPA in MRI surface RAS coordinates, you can uniquely define the MRI<->head transformation, and it will never (in practice) be identity.


Ok I follow everything except this. Isn't the goal that they be exactly the same and any difference due to user error?

**Comment by larsoner** [comment]
The goal that what be the same? The MRI coordinate frame is scanner dependent and in practice isn't ever the head coordinate frame (as defined by LPA/Nasion/RPA), so you need some transformation to get from one to the other.

In principle given an MRI, there is one correct/best transformation from that to head. You can estimate it several ways: by manually clicking points on the MRI (mne coreg + get_ras_to_neuromag_trans), by estimating fiducial locations using MNI transformation (get_mni_fiducials + get_ras...), or by fitting digitized head points and trusting your digitizer (mne coreg directly). In principle if everything is perfect these all give the same locations and head<->MRI transformation. In practice, for sEEG using the locations estimated from MNI to get the transformation should be good enough I think.

So basically I think we should say for now that to establish one consistent coordinate frame that's used a lot in MNE (head) we should keep track of these properly. In the end I don't think it's so complicated to automatically (in the GUI) give people fiducials using MNI. Then the users just have to keep track of the trans, which they can get from some new function like estimate_head_mri_t that uses the MNI fiducials plus the MNI transformation.

I know wrangling these has posed some challenges, but at the end of the day I don't think it'll be too onerous for the user, and it helps keep things consistently and correctly defined and used throughout MNE. A week or so from now I can help push the coordinate frame stuff forward if you need help sorting out how to refactor the plot_alignment coordinate frame stuff.

I won't have time to respond much more (if at all) before then, but this is at least the direction I'd rather see things go. Hopefully @drammock can also help guide in this direction (assuming it makes sense to him as well!)

**Comment by alexrockhill** [comment]
So rereading the coordinate frame documentation that you were referencing (https://mne.tools/dev/auto_tutorials/forward/20_source_alignment.html) I think this part conflicts with what you were saying earlier about digitizer coordinates being in the unknown coordinate frame

Screen Shot 2021-08-08 at 10 57 20 AM

Screen Shot 2021-08-08 at 10 56 49 AM

If the fiducials found by the digitizer define the head coordinate frame, I think what makes the most sense is to say that the MRI is the digitizer (or rather the CT aligned to the MRI) and the fiducial coordinates in that image define head space which also happens to be the same as surface RAS.

What's confusing to me is that you keep referencing fiducials that appear from nowhere. As far as I understand it, they have to be digitization points from equipment such as a Polhemus device. In using the coregistration GUI, I have only ever aligned fiducial points that already exist (and that have a fixed positional relationship to the other points) with the anatomical landmarks on the reconstructed head. Since, for intracranial recordings, there are no recorded fiducial points (other than those selected from the CT/MR), as far as I understand it there is no "head" coordinate frame besides the one you could choose to define based on the fiducials in the MRI which would equate "head" and "mri". The concept of a "head" coordinate frame as I understand it is based on fiducial points that were recorded in reference to a device-specific coordinate frame which only applies to MEG and scalp EEG where those points are essential for defining coordinate frames to transform locations of recording contacts. In the case of intracranial recordings where there is no device measuring fiducials or defining another coordinate frame, it seems very confusing to make one up. I'm following what you're saying but I still have not heard a clear explanation of where the fiducials that define this coordinate frame are coming from and the logical conclusion I am drawing from that is that the coordinate frame doesn't exist and I think you may be overcomplicating this.

**Comment by larsoner** [comment]
> What's confusing to me is that you keep referencing fiducials that appear from nowhere

LPA Nasion RPA are physical landmarks on people. You can estimate where they are in any coordinate frame (Polhemus native if using a digitizer, MRI surface RAS if looking at an MRI, etc.). Each point in that given space has some XYZ coordinate *in that coordinate frame*. In general, each of the X, Y, Z values will be non-zero.

> as far as I understand it there is no "head" coordinate frame besides the one you could choose to define based on the fiducials in the MRI

This part is correct ...

> which would equate "head" and "mri".

... This part is not. The two frames are not the same. In general they are rotated and translated relative to one another. This is just like during an MEG recording, there is a device coordinate frame and a head coordinate frame and a MRI coordinate frame (optionally). None of these are equivalent -- they are all rotated and translated relative to each other. However, you can express any given point (e.g., a sensor, or a brain source) in any of these three frames if you have the (practically always non-identity) transformations between them. We wouldn't say that the MEG device coordinate frame (which is relative to the helmet) is the same as the head or MRI coordinate frame, even though points can be represented just as well and equivalently in any of these frames.

In other words, my operating definition (and I think the standard one?) is that two frames are equivalent if and only if the transformation between them is an identity matrix. This is not the case for MRI surface RAS and the head coordinate frame in any realistic use case.

Maybe this is what's confusing you, that points can be equivalently expressed in these different frames / they are all different ways of representing the points for a given subject? 

> The concept of a "head" coordinate frame as I understand it is based on fiducial points that were recorded in reference to a device-specific coordinate frame

No, everyone has one correct head coordinate frame based on their physical real-life locations of LPA Nasion RPA (as physical points on the person).

The cool thing is that if you can identify these three points on a person in any *other* coordinate frame, such as MRI or native digitizer or montage, you can compute the transformation to their head coordinate frame. The accuracy of this transformation depends on the accuracy of localizing those three points in the *other* coordinate frame of interest.

If correctly defined, LPA will have the form -L,0,0, RPA +R,0,0, and Nasion at +0,N,0 for some suitable positive values L,R, and N. This is different from their states in, say, MRI coordinates, which will in general have XYZ all non-zero. This implies that the coordinate frames are not the same, even though they are representing the same points.

**Comment by alexrockhill** [comment]
> No, everyone has one correct head coordinate frame based on their physical real-life locations of LPA Nasion RPA (as physical points on the person).

This makes no sense to me. The real-life location of your fiducials changes over time as you move around in the real world. Digitization systems such as Polhemus simply record one of those positions at a fixed point in time. The difference between this and the MR/CT capturing the physical locations of fiducial markers at another arbitrary fixed point in time escapes me.

**Comment by larsoner** [comment]
> The real-life location of your fiducials changes over time as you move around in the real world

You have to keep in mind the frame of reference. These points do change location relative to the earth, but they don't (at least on the time scale of the MR/CT/sEEG) change relative to the head coordinate frame. They are fixed in that frame. So I think the discussion of time here is not really relevant.

> Digitization systems such as Polhemus simply record one of those positions at a fixed point in time.

Agreed! But I think the more important point is that they record them relative to the native Polhemus device frame, whatever that is.

> The difference between this and the MR/CT capturing the physical locations of fiducial markers at another arbitrary fixed point in time escapes me.

The time doesn't matter here, since one's head geometry is fixed enough for our use cases (is assumed static over the time span of CT/MRI/sEEG). What you get with an MRI is another set of XYZ locations of points like L/N/R.

We could define another coordinate frame "foo" using the line-intersections of any three non-colinear points, and as long as we could reliably localize those three points in a given "image"/space of any type (like an MRI, or Polhemus device) we could define a MRI<->foo transformation automatically (and this would in general not be identity).

I'm not sure how else to explain this, maybe a chat in a couple of weeks would help, or maybe @drammock could do a better job of explaining it!

**Comment by alexrockhill** [comment]
Ah okay, I think what I was missing was that the digitizer is in the device coordinate frame (aka unknown not to be confused with the MEG device coordinate frame) and that those points are transformed to the head coordinate frame via the fiducial points.

So then the way it was before was good enough where, if you have the Freesurfer recon-all, you can get an estimate of fiducial points from the Talairach inverse and use those to construct a fiducial coordinate frame. I think this is very complicated to explain why this is happening in the use-case of sEEG but I think maybe mentioning that the "head" coordinate frame requires fiducials for its definition and then explaining that we don't have any but we can estimate them fairly easily and that their accuracy isn't important, only their consistency. Still seems like a complicated narrative but I guess that's the best that can be done without requiring fiducials as input.

I'll close this and put back the sensors one and then I think everything is on the right track. Thanks for explaining!

**Pull request closed without merging**
