### PR TITLE
[ENH] Add the rest of the freesurfer recon for the aseg files

### PR DESCRIPTION
**Pull request by alexrockhill**
For the examples, I need the aseg files but I thought it would be worth adding the rest of the mri files for plotting in the future. Happy to delete any extraneous files.

### CODE REVIEW

**Comment by larsoner** [comment]
```
larsoner@bunk:~/python/MNE-misc-data/seeg$ du -hs
93M	.
larsoner@bunk:~/python/MNE-misc-data/seeg$ git branch
* master
larsoner@bunk:~/python/MNE-misc-data/seeg$ git checkout -b seeg2 alexrockhill/seeg2
Branch 'seeg2' set up to track remote branch 'seeg2' from 'alexrockhill'.
Switched to a new branch 'seeg2'
larsoner@bunk:~/python/MNE-misc-data/seeg$ du -hs
284M	.
```
This is actually smaller than I expected. Still, it does seem like there are some easy targets for removal that I have never seen used (plus one file with a `~` that is probably safe to remove):
```
BIN +1.08 MB seeg/sample_seeg/mri/brainmask.mgz~ 
BIN +31.4 MB seeg/sample_seeg/mri/transforms/talairach.m3z 
BIN +5.68 MB seeg/sample_seeg/surf/lh.cvs.tocvs_avg35_inMNI152.sphere.reg
BIN +5.35 MB seeg/sample_seeg/surf/lh.seghead.inflated
BIN +5.68 MB seeg/sample_seeg/surf/lh.white.preaparc
BIN +5.71 MB seeg/sample_seeg/surf/rh.cvs.tocvs_avg35_inMNI152.sphere.reg
BIN +5.71 MB seeg/sample_seeg/surf/rh.white.preaparc 
```
Removing these brings us down to 225 MB. To me it seems worth it to make the recon "incomplete" to save 20%. WDYT? Any others you think we can safely remove?

I think it's also okay to remove these since if people really want them, they can get them (e.g., `talairach.m3z`) easily from https://surfer.nmr.mgh.harvard.edu/fswiki/ReconAllTableStableV6.0

**Comment by agramfort** [comment]
please keep this repo as small as possible

>

**Comment by larsoner** [comment]
If adding another 100 MB here is too much, we could pretty easily split this off into a `mne.datasets.seeg.data_path()`. Up to you @agramfort ...

**Comment by alexrockhill** [comment]
> If adding another 100 MB here is too much, we could pretty easily split this off into a `mne.datasets.seeg.data_path()`. Up to you @agramfort ...

I'm fine adding files as needed, it just makes more PRs as we seem to be adding back much of the Freesurfer output. I'll do a minimal version now.

**Comment by alexrockhill** [comment]
Looks like about 40 MB now just by a rough count scrolling through, I think we could optimize more but this is really nice stuff to have for visualizations

**Comment by agramfort** [comment]
40MB is ok.

it's true that it offers nice "eye candies" :)

>

**Comment by larsoner** [comment]
Last request from me is to add back `sphere` and `sphere.reg` surfaces. This will be needed for any surface morph operation. With these plus the files you have here I think every built-in MNE function will work.

**Comment by alexrockhill** [comment]
That extra 20 MB is on you @larsoner ;)

**Comment by alexrockhill** [comment]
Ok, I think good to merge unless there are any more suggestions

**Comment by larsoner** [comment]
Released 0.15

**Pull request merged**
