### PR TITLE
[BUG, MRG] Add aseg.mgz

### PR DESCRIPTION
**Pull request by alexrockhill**
Oops somehow I missed `aseg.mgz`, also `lh.seghead` might be nice while we're at it. This caused the doc build failure.

### CODE REVIEW

**Comment by larsoner** [comment]
We are already on 0.15:

https://github.com/mne-tools/mne-misc-data/commit/b18cb862a76dbf4b3a6fdb1eabbe40096fb3bad3

And `lh.sphere` for example already exists:

https://github.com/mne-tools/mne-misc-data/blob/master/seeg/sample_seeg/surf/lh.sphere

But looking at the diff these files show up as added:

https://github.com/mne-tools/mne-misc-data/pull/10/files#diff-61b56355d0c68bc88e87a0c5e23eca3fb2d7efb6e75d2a4f7401e6580612b8fa

So I'm confused

**Comment by larsoner** [comment]
Okay that looks better :)

**Comment by alexrockhill** [comment]
> We are already on 0.15:
> 
> [b18cb86](https://github.com/mne-tools/mne-misc-data/commit/b18cb862a76dbf4b3a6fdb1eabbe40096fb3bad3)
> 
> And `lh.sphere` for example already exists:
> 
> https://github.com/mne-tools/mne-misc-data/blob/master/seeg/sample_seeg/surf/lh.sphere
> 
> But looking at the diff these files show up as added:
> 
> https://github.com/mne-tools/mne-misc-data/pull/10/files#diff-61b56355d0c68bc88e87a0c5e23eca3fb2d7efb6e75d2a4f7401e6580612b8fa
> 
> So I'm confused

Sorry I had some commits saved and I committed on top, my bad.

**Comment by larsoner** [comment]
0.16 released, cc7924e6010b5ba51626ccd041451493

**Pull request merged**
