### PR TITLE
[ENH, MRG] Fix positions and cruft

### PR DESCRIPTION
**Pull request by alexrockhill**
So the way I had the GUI before just subtracted the positions by (128, 128, 128) to convert from voxel RAS (reoriented) surface RAS but the transform matrix, when computed correctly is a bit surprisingly:

```
array([[   1.,    0.,    0., -127.],
       [   0.,    1.,    0., -128.],
       [   0.,    0.,    1., -127.],
       [   0.,    0.,    0.,    1.]])
```

So I adjusted for that, and while I was there I redid a few of the electrode contact positions as well. This works for the example with `CT_thresh=0.95` now even on `zooms=5`!

### CODE REVIEW

**Comment by alexrockhill** [comment]
@drammock, could you merge this please if it looks okay to you? It's just some cruft and electrode position improvements.

**Comment by drammock** [comment]
It seems I don't have merge rights on `mne-misc-data` (?) and I can't even see if there's anyone else to ping besides @larsoner or @agramfort

**Comment by alexrockhill** [comment]
Ah right then, bummer, I guess this will have to wait to merge until next week then

**Comment by larsoner** [comment]
Now you have permissions @drammock

**Comment by drammock** [comment]
ok, 0.19 is released @alexrockhill

**Pull request merged**
